return (
  <a
    href={
      post.href ??
      "https://instagram.com/justwaxbykim"
    }
    target="_blank"
    rel="noopener noreferrer"
    className="
      group
      relative
      block
      aspect-square
      overflow-hidden
      rounded-[20px]
      border
      border-[#E8DDD8]
      bg-[#F6E7E1]
      transition-all
      duration-500
      hover:border-[#D4A9B6]
    "
  >
    <Image
      src={post.image}
      alt={post.alt}
      fill
      className="
        object-cover
        transition-transform
        duration-700
        group-hover:scale-105
      "
    />

    <div
      className="
        absolute
        inset-0
        bg-gradient-to-t
        from-[#3B2A26]/20
        via-transparent
        to-transparent
        opacity-0
        transition-opacity
        duration-500
        group-hover:opacity-100
      "
    />
  </a>
);
